name: Update "What I'm working on"

on:
  # Run this workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"
  # Also run it any time you push to your profile repo
  push:
    branches:
      - main
      - master
  # And let you trigger it manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# Make sure only one update job runs at a time (avoids overlapping edits)
concurrency:
  group: update-working-on
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update README with latest push
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            // Figure out your username (owner of this profile repo)
            const owner = context.repo.owner;

            // Get your public repos, sorted by most recently pushed.
            // This uses listForUser instead of listForAuthenticatedUser,
            // which works with the default repo-scoped GITHUB_TOKEN.
            const { data: repos } = await github.rest.repos.listForUser({
              username: owner,
              per_page: 100,
              sort: 'pushed',
              direction: 'desc'
            });

            // Pick the most recently pushed, skipping forks/archived.
            const recent = repos.find(r => !r.fork && !r.archived);
            if (!recent) {
              core.setFailed('Couldn’t find a recent active repository.');
              return;
            }

            // Grab the latest commit from that repo so we can show it off.
            const { data: commits } = await github.rest.repos.listCommits({
              owner: recent.owner.login,
              repo: recent.name,
              per_page: 1
            });
            const latest = commits[0];

            // Build a short, friendly line of text with the repo name, commit hash,
            // first line of the commit message, and the push timestamp (UTC).
            const pushedAt = new Date(recent.pushed_at)
              .toISOString()
              .replace('T',' ')
              .replace('Z',' UTC');

            const firstLine = (latest?.commit?.message || '').split('\n')[0] || 'no commit message';
            const line = `**${recent.full_name}** — latest commit: ${latest.sha.slice(0,7)} — _${firstLine}_  \nPushed: ${pushedAt}  \nRepo: https://github.com/${recent.full_name}`;

            // Drop that line into your README between the START/END markers.
            const path = 'README.md';
            const start = '<!--START_SECTION:working_on-->';
            const end = '<!--END_SECTION:working_on-->';
            let readme = fs.readFileSync(path, 'utf8');

            if (!readme.includes(start) || !readme.includes(end)) {
              core.setFailed('README markers not found. Make sure START/END markers are present.');
              return;
            }

            const newSection = `${start}\n${line}\n${end}`;
            const regex = new RegExp(`${start}[\\s\\S]*?${end}`);
            const updated = readme.replace(regex, newSection);

            if (updated !== readme) {
              fs.writeFileSync(path, updated);
              core.info('README updated.');
            } else {
              core.info('README content unchanged; nothing to write.');
            }

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README with latest project activity"
