name: Update "What I'm working on"

on:
  # Run this workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"
  # Also run it any time you push to your profile repo
  push:
    branches:
      - main
      - master
  # And let you trigger it manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# Make sure only one update job runs at a time (avoids overlapping edits)
concurrency:
  group: update-working-on
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update README with latest push
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            // Look up all of your repos, sorted by most recently pushed.
            // Skip forks and archived projects – we only care about active work.
            const { data: repos } = await github.rest.repos.listForAuthenticatedUser({
              per_page: 100,
              sort: 'pushed',
              direction: 'desc'
            });
            const recent = repos.find(r => !r.fork && !r.archived);
            if (!recent) {
              core.setFailed('Couldn’t find a recent active repository.');
            }

            // Grab the latest commit from that repo so we can show it off.
            const { data: commits } = await github.rest.repos.listCommits({
              owner: recent.owner.login,
              repo: recent.name,
              per_page: 1
            });
            const latest = commits[0];

            // Build a short, friendly line of text with the repo name, commit hash,
            // first line of the commit message, and the push timestamp.
            const pushedAt = new Date(recent.pushed_at).toISOString().replace('T',' ').replace('Z',' UTC');
            const line = `**${recent.full_name}** — latest commit: ${latest.sha.slice(0,7)} — _${latest.commit.message.split('\\n')[0]}_  \nPushed: ${pushedAt}  \nRepo: https://github.com/${recent.full_name}`;

            // Drop that line into your README between the START/END markers.
            const path = 'README.md';
            const start = '<!--START_SECTION:working_on-->';
            const end = '<!--END_SECTION:working_on-->';
            let readme = fs.readFileSync(path, 'utf8');

            const section = `${start}\n${line}\n${end}`;
            const regex = new RegExp(`${start}[\\s\\S]*?${end}`);
            readme = readme.replace(regex, section);

            fs.writeFileSync(path, readme);

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): update working on section"
